server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://dpg-d1ml3dje5dus73as0ca0-a.oregon-postgres.render.com:5432/microservices
    username: scm20_o9v8_user
    password: JuWIGA7KOtbPriGPSQacK6Z0XbmBpbvT
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:https://config-server-microservices-hotel.onrender.com


#  profiles:
#    active: dev

eureka:
  instance:
    hostname: user-microservices-hotel.onrender.com
    prefer-ip-address: false
    instance-id: user-microservices-hotel.onrender.com
    status-page-url: https://user-microservices-hotel.onrender.com/actuator/info
    health-check-url: https://user-microservices-hotel.onrender.com/actuator/health
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://service-regsistry-microservices-hotel.onrender.com/eureka/


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s



#
#
#
#

#
#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:postgresql://dpg-d1ml3dje5dus73as0ca0-a.oregon-postgres.render.com:5432/microservices
#    username: scm20_o9v8_user
#    password: JuWIGA7KOtbPriGPSQacK6Z0XbmBpbvT
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#  application:
#    name: USER-SERVICE
#
#  config:
#    import: configserver:http://localhost:8085
#
##  profiles:
##    active: dev
#
#Eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health
#
#  endpoint:
#    health:
#      show-details: always
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      ratingHotelBreaker:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 6s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
#
#  retry:
#    instances:
#      ratingHotelService:
#        max-attempts: 3
#        wait-duration: 5s
#
#
#
#
#
#
#
